#!/bin/bash

#I have divided the script into 3 parts...
#Part 1 :: Here We are Running the AWS Inspector scan and waiting untill it completes the scan
#Part 2 :: Next we are downloading the report of that scan generated by inspector into the server where this script is running
#Part 3 :: Then we are sending this Report to an email address. 

#PRERQUISITES :: 
## To run this scrip firstly we will need to set upt the postfix and configure it accordingly.
## We will need to install the [mutt] package to send the email.





#PART 1 --------------------------------------------------
# Set the variables
AWS_REGION="us-east-1"
ASSESSMENT_TEMPLATE_ARN="arn:aws:inspector:us-east-1:161786843916:target/0-ptyjBgbD/template/0-DXuMsqUo"

# Start the AWS Inspector scan and get the scan ARN
SCAN_ARN=$(aws inspector start-assessment-run --assessment-template-arn $ASSESSMENT_TEMPLATE_ARN --output text)
echo " "
echo "Inspector Scan has been started..."
sleep 3
# Wait for the scan to complete
while true; do
  # Get the scan status
  SCAN_STATUS=$(aws inspector describe-assessment-runs --assessment-run-arns $SCAN_ARN --query 'assessmentRuns[0].state' --output text)
  echo " "
  echo "Scan status: $SCAN_STATUS"
  sleep 2
  # Check if the scan is completed
  if [ "$SCAN_STATUS" == "COMPLETED" ]; then
    break
  fi
  sleep 3
done
echo " "
echo "Scan is Completed successfully"
sleep 5
echo " "
echo "Prepairing Scan report, this will only take few seconds"
sleep 5





#PART 2 -------------------------------------------------
#Donloading the latest scan run's report to the server
latest_run_arn=$(aws inspector list-assessment-runs --assessment-template-arn arn:aws:inspector:us-east-1:161786843916:target/0-ptyjBgbD/template/0-DXuMsqUo --filter states=COMPLETED --max-results 1 | jq -r '.assessmentRunArns[0]')
report=$(aws inspector get-assessment-report --assessment-run-arn $latest_run_arn --report-file-format "PDF" --report-type "FULL" | jq -r '.url')
curl -s -o /home/ubuntu/report.pdf $report
echo " "
echo "Report has been downloaded locally in this serever"
sleep 5




#PART 3 -------------------------------------------------
#Install Postfix, do the configuration
#Then install mutt :: sudo apt-get install mutt
echo -e "Hi,\n\nPlease find attached report of the AWS Inspector scan.\nYou can also check the findings here : https://us-east-1.console.aws.amazon.com/inspector/home?region=us-east-1#/run\n\nThanks,\nKandyman" | mutt -a /home/ubuntu/report.pdf -s "Inspector Scan Findings/Report" -- simranbanwait02@gmail.com
echo " "
echo "Report has been sent via email SUCCESSFULLY..." 
sleep 5
